### ISSUE TITLE
Bug: image texture can't be unbound from an FBO.

### ISSUE THREAD

**Issue by manhnt9** [buildaworldnet/IrrlichtBAW#158]
I have an FBO.
I attach nullptr to every attachment points I use before for this FBO.
I call rebindRevalidate() on that FBO.
I remove that FBO.

Create another FBO, just add a new one, no other calls.
Blit new FBO to screen.
Old texture attachment of the destroyed FBO appears.
This is why OpenCL interop fails to read textures since they're still being used foreverrrrr.

**Comment by devshgraphicsprogramming** [comment]
Did you setRenderTarget or blit using the first FBO?
Can you post a full code snippet?
And can I get a renderdoc capture (dont create a sharing OpenCL context, so rdoc doesn't crash)?

In at least one part it looks like this is perfectly legal engine behaviour.
If stems from many aspects of the engine and OpenGL.

First is the fact that the engine does not tolerate zero-attachment FBOs, and neither does OpenGL 4.3 without explicitly setting the FBO properties it would derive from the attachments (such as resolution, sample count).
When blitting using the new FBO, you will most probably hit (if you dont provide a source rect):
https://github.com/buildaworldnet/IrrlichtBAW/blob/master/source/Irrlicht/COpenGLDriver.cpp#L2939
https://github.com/buildaworldnet/IrrlichtBAW/blob/master/source/Irrlicht/COpenGLFrameBuffer.cpp#L44
So you will effectively not get a blit, at all (silent fail)!

Secondly are you attaching `nullptr` when this FBO is unbound (not currently used as render target)?
Its hard for me to check what would happen in such a scenario, when an FBO is bound to the DRAW/READ targets but you go changing attachments while its in use... would have to read OpenGL spec for this.
Nevertheless you should make sure your FBO is not in use by the API (not GPU) if you want to modify things in it, so make sure other FBO is active render target.

rebindRevalidate will return `false` on an FBO due to the first point, but FBO->attach(nullptr) will detach your textures.
https://github.com/buildaworldnet/IrrlichtBAW/blob/master/source/Irrlicht/COpenGLFrameBuffer.cpp#L144

A possible bug here on our side is what happens is DRAW_BUFFERS is set on a framebuffer and the textures are detached.


Last point is that while IrrBAW destroys your objects (as long as your ref-counting is correct), OpenGL does not care... it does its own ref-counting and keeps objects around until their last use.

**Comment by manhnt9** [comment]
I only setRenderTarget and clear old FBO. And I don't provide rect for blit.
My bit call is ```blitRenderTargets(fbo, nullptr, false)```

Old FBO is still a render target when I attach null to attachment points.
Then I set render target to null also.
Then rebindRevalidate and remove that FBO.

I'm gonna try disable OpenCL and capture a render doc file.

**Comment by manhnt9** [comment]
Captured with RenderDoc v0.92
[fbo.zip](https://github.com/buildaworldnet/IrrlichtBAW/files/2522618/fbo.zip)

**Comment by devshgraphicsprogramming** [comment]
> My bit call is blitRenderTargets(fbo, nullptr, false)

Yeah in that case blit will not be performed !

> Then I set render target to null also.

You should set render target to null first and then detach attachments

Btw passing null to setRenderTarget will detach it from GL_DRAW_FRAMEBUFFER and GL_READ_FRAMEBUFFER
https://github.com/buildaworldnet/IrrlichtBAW/blob/master/source/Irrlicht/COpenGLDriver.cpp#L3047

**Comment by devshgraphicsprogramming** [comment]
Found a slight issue, the COpenGLExtensionHandler::extGlClearNamed* functions should be using 
GL_DRAW_FRAMEBUFFER targets instead of GL_FRAMEBUFFER for the non-DSA implementations.

But you have a 1050Ti and OpenGL 4.5, so thats definitely not the issue.

**Comment by devshgraphicsprogramming** [comment]
Actually I don't know why but RenderDoc is showing that you're using the non-DSA (ARB nor EXT) entry points for ClearBuffer etc. , can you step-through and show which branch of COpenGLExtensionHandler::extGlClearNamed* you're hitting?

Or is it RenderDoc lying to me?

**Comment by devshgraphicsprogramming** [comment]
you never drew to the FBO in the first place.. so the bug is probably in your code.

I'm going to keep this issue open because of the interesting issue of clearing not using GL_DRAW_FRAMEBUFFER bind points in non-DSA implementations and Render Doc possibly lying about what entry points are being used.

**Comment by manhnt9** [comment]
Solved on Skype chat with @devshgraphicsprogramming , I'm not attaching textures correctly, so drawing goes to screen instead of render target.
What's on the screen isn't previous texture bound to the destroyed FBO.
