### ISSUE TITLE
VS 2017 CMAKE Build Issues

### ISSUE THREAD

**Issue by vutle** [buildaworldnet/IrrlichtBAW#188]
Hi I try to get CMAKE gui to create build. But encounter library not found.

![image](https://user-images.githubusercontent.com/6241928/48924548-7a48ba00-ef0d-11e8-9ac5-12b0484dec57.png)

Build the source will encounter this error below.

![image](https://user-images.githubusercontent.com/6241928/48924592-f2af7b00-ef0d-11e8-9820-f2332cde9398.png)

**Comment by devshgraphicsprogramming** [comment]
Two questions:
1) Did you set up OpenSSL in the right place (or at all)?
2) Can you paste the full text of the VS 2017 compile errors, as right now I don't see what file+line the error concerns

**Comment by devshgraphicsprogramming** [comment]
Also try with my newest commits to the stable-ish branch

**Comment by Crisspl** [comment]
@vutle, if `NASTY_OPENSSL_WORKAROUND` is ON, then (as described in [Wiki article](https://github.com/buildaworldnet/IrrlichtBAW/wiki/Building-The-Library)), should openssl's root dir should be in `..` relatively to Irrlicht's root dir. Since this is Windows and you never know how things are, currently cmake script assumes that openssl dir looks like this:  
```
irrlicht_root/../openssl/  
--- lib/  
------ libeay32.lib  
--- include/  
------ openssl header files...  
```

The other way is to uncheck this `NASTY_OPENSSL_WORKAROUND` option and manually provide paths to eay lib to `SSL_EAY_DEBUG`, `SSL_EAY_RELEASE`, `LIB_EAY_DEBUG` and `LIB_EAY_RELEASE` cmake vars and path to include dir to `OPENSSL_INCLUDE_DIR`.  
  
As for errors you experience: apparently MSVC is a little buggy and doesn't inherit default constructor. Already fixed, so you can build from my fork, branch fix or wait wait until @devshgraphicsprogramming merge my PR and build from his stable-ish branch.

**Comment by devshgraphicsprogramming** [comment]
Once I verify it builds from CMake on my windows laptop I close the issue

**Comment by devshgraphicsprogramming** [comment]
@Crisspl I have a massive error with my cmake-gui, it generates win32 visual studio targets not x86!

Why is it trying to make a 32bit build target instead of 64bit?

**Comment by Crisspl** [comment]
I think, you have to choose other compiler/IDE option in cmake-gui if i remember correctly (there are 2 distinct options for x86 and x86_64). I had same issue once and it was the problem. Apprently i forgot to place it into the wiki, sorry

**Comment by devshgraphicsprogramming** [comment]
Works like a charm, closing
