### ISSUE TITLE
[STUB] Finish GPU sorting

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [buildaworldnet/IrrlichtBAW#281]
Page 99:
https://frostbite-wp-prd.s3.amazonaws.com/wp-content/uploads/2016/03/29204330/GDC_2016_Compute.pdf

**Comment by Lumirion** [comment]
Why not develop two rtree variants, one for the scene manager and one on the gpu.  On the cpu this would accelerate path finding, collision detection, and culling by using nearest neighbor searches. Using an rtree means the spatial index doesn't have to be rebuilt entirely from scratch every frame.  It is efficient to balance and maintain. With an rtree irrelevant data can be skipped. Most nodes in the rtree won't need to be sorted every frame.  Only nodes affected by animations/movement need to be updated.  These updates can span about 5 to 10  frames with little visual glitching for objects farther from the camera. Nearer animated objects may need to be processed more often. The rtree functions should be multi threaded.  On the gpu, triangle strips can be stored under the meshes containing them.  When generating the triangle list that will be rendered, start nearest to the camera and stop looking at the first solid triangle that fully covers the pixel. The, below linked, blog on Triangle Visibility Buffer; provides examples for a degenerate triangle test and small primitive test.  Degenerate triangles are any triangles which, in the current animated state, have any two points being equal.  This defines a line and not a triangle so it can’t render this frame anyway.  The small primitive test collapses and scales a triangle into two dimensional screen space and tests if it overlaps a pixel center.  If it does not then it is culled since the rasterizer won’t pick it this frame anyway. The OIT techniques, I have researched, suggest that at a depth of about 8 transparent fragments no further fragments will have a noticeable effect on the pixel.  So if we count to a depth of 8 fully covering triangles we don't need any more and the rest can be culled.

Rtrees are beneficial for collision detection so only the nearest collision planes need to be checked. Being dynamic, rtrees are great for level management tasks like streaming levels from disk. And for post processing, volume effects.


References
Https://www.scitepress.org/Papers/2015/53048.off.  Accelerated Ray Tracing using R-Trees.

https://www.researchgate.net/figure/The-cluster-hierarchy-is-used-at-runtime-to-perform-occlu-sion-culling-On-the-left-the_fig2_4046780. Interactive View-Dependent Rendering with Conservative Occlusion Culling in Complex Environments

https://diaryofagraphicsprogrammer.blogspot.com/2018/03/triangle-visibility-buffer.html  Triangle Visibility Buffer

**Comment by devshgraphicsprogramming** [comment]
@Lumirion great input, but this issue is about sorting of arrays only, as in the simple algorithmic/computational primitive. This is about finishing ex 03

As for OIT, we already have an 8 layer OIT technique in example OITZoo with the stencil-k-routed algorithm.

**Comment by devshgraphicsprogramming** [comment]
This is now a recruitment task for Nabla.
