### ISSUE TITLE
How to use the new Shader, GraphicsPipeline and DescriptorSet API

### ISSUE THREAD

**Issue by AnastaZIuk** [buildaworldnet/IrrlichtBAW#383]
It will be used for writing wiki page

**Comment by AnastaZIuk** [comment]
So, what is the purpouse of `IPipelineLayout` interface? I see that it has some "layouts" (4), const "ranges", can specify shader stage, offsets (for what?) and is associated with Descriptor Sets a little bit.

And what is actaully `Descriptor Set` by itself? What is a difference between `Descriptor Set` and `Descriptor Set Layout`? What do their responsibility look like?

> You can over-declare descriptor set layouts, i.e. a set that has every single resource and more that a 
> shader could use (all the textures, all the buffers for all shader types).

Is `Descriptor Set Layout` a binding between set of attributes in shader, where single `Descriptor Set` binds with appropriate attribute? (in opengl case though)
In the other hand, such a Descriptor could be an image sampler or even a uniform buffer, so it discards question above

**Comment by AnastaZIuk** [comment]
Both `IDescriptorSetLayout` and `IDescriptorSet` have some binding. How is a correlation between them? And is there any actaully if it comes to bindings?

**Comment by devshgraphicsprogramming** [comment]
> So, what is the purpouse of IPipelineLayout interface?

Stores all the state (options) common to multiple draw calls (meshes) as an aggregate. It exists because the same object exists in the Vulkan API, you should probably find some good references and read those about its full purpose.

But quickly skimming over the topic, I can say that in OpenGL and D3D11 there often was a situation where changing a Raster State (fixed function setting such as alpha blending equation, or depth comparison mode) caused a shader recompile and a hick-up while rendering because most GPUs are not 100% as fixed function as the Graphics API specificiation (on AMD there are no hardware units for pixel shader interpolation, on mobile the blending is programmable).

The pipeline object gathers all the information about the resources (types) and settings you'll be using while rendering, so that there are no nasty surprises in the "hot" render-loop.

**Comment by devshgraphicsprogramming** [comment]
>  I see that it has some "layouts" (4), const "ranges", can specify shader stage

There's the pipeline layout and the descriptor set layout, its easier to discuss the descriptor set layout first.

The descriptor set layout is a template, it specifies the bindings (in the shader GLSL interfaces), counts and types of resources (UBO, SSBO, combined image samplers, storage images) that will be used by the shader stages (the shader stage flag, vertex, fragment, etc.). This template is used to create descriptor sets (handle to a bundle of resources) which specify the actual resources (not the types) that will be used by a shader at execution time.

Descriptor Sets are an improvement over the legacy API (OpenGL, DirectX11) way of binding resources, whereas resources had to be bound 1 by 1, they are instead bound all at once for a bundle.

However because certain resources have a different frequency of binding (per mesh texture vs. a shadowmap for an entire scene) there are up to 4 separate slots for 4 separate descriptor sets so that all the resources can be broken down into descriptor sets which allow them to be bound somewhat more independently (but not on a 1 by 1 granularity).

The Pipeline Layout specifies all 4 templates of resource types ( a null descriptor layout is an empty template) that will be used by all the shaders used in the draw or compute dispatch. This is to allow for faster validation and execution of the hot loop, as most of the validation of shader GPU inputs and program CPU outputs has now been hoisted to pipeline creation time.

The pipeline layout is a separate from the pipeline object to allow the creation of multiple pipelines that may have different shader code but which we want to remain compatible with each other so that switching between them is less expensive than between unrelated pipelines.

To provide an analogy, you should think of Layouts (PipelineLayout, DescriptorSetLayout) as C++ data type declarations, and the objects created from layouts (RenderpassIndependentPipeline, ComputePipeline, DescriptorSet) as particular objects of said type created in memory. 

>offsets (for what?)

Can you reference the code so I know which offsets we're talking about?

**Comment by AnastaZIuk** [comment]
What is a purpouse of `IRenderpassIndependentPipeline` interface? 
It has at all much to do, set vertex formats and bindings, it shares many enums for begginnig params of pipeline and more, but how does it combine with`DescriptorSets` and `DescriptorSetLayouts`?
Has `ICPURenderpassIndependentPipeline` some functionality that `video::SCPUMaterial` had had?

**Comment by devshgraphicsprogramming** [comment]
> And what is actaully Descriptor Set by itself? What is a difference between Descriptor Set and Descriptor Set Layout? What do their responsibility look like?

Its a collection of buffers, textures and sampling parameters that you can specify to be bound for the shader to be able to access them while drawing or compute dispatching.

Again, set layout is the template, the set is an actual object created according to that template.

**Comment by AnastaZIuk** [comment]
Well, `IPipelineLayout` itself doesn't have offsets, but it has smart ref counted dynamic array of SPushConstantRange that owns offset

`struct SPushConstantRange
{
    E_SHADER_STAGE stageFlags;
    uint32_t offset;
    uint32_t size;
...
}`

**Comment by devshgraphicsprogramming** [comment]
> Is Descriptor Set Layout a binding between set of attributes in shader, where single Descriptor Set binds with appropriate attribute? (in opengl case though)

The DescirptorSetLayout tells the engine, at each used GLSL binding, how many and of what type are the resources.

DescriptorSet is a collection of resources conforming to the template given by DescriptorSetLayout, in other words the DescriptorSet has to have the exact same number and type of resources as specified by the Layout.

Buffers, Images and Samplers all derive from `IDescriptor` and can be bound under different bindings in a DescriptorSet, so that they can be bound to the GPU API together in a single API call with efficiency.

**Comment by devshgraphicsprogramming** [comment]
> Both IDescriptorSetLayout and IDescriptorSet have some binding. How is a correlation between them? And is there any actaully if it comes to bindings?

a GLSL shader declares resources with `layout(set=N, binding=M) TYPE name[K];`

The DescriptorSetLayout shall at least contain a binding declaration specifying each resource for the same value of `N` with the correct `M`, `TYPE`, and `K` for that particular resource.

There should be as many DescriptorSetLayout objects as there are different values of `N`, obviously some DescriptorSetLayout objects would have the exact same contents/definition so those can be shared (no need to create duplicate objects). If you wish to know more about this optimization read the Vulkan "Pipeline Compatibility" section in the spec.

The application has complete freedom in how it associates/binds DescriptorSets to the GLSL `set=` bindings (not so much for the `binding` or array count).

**Comment by devshgraphicsprogramming** [comment]
> Has ICPURenderpassIndependentPipeline some functionality that video::SCPUMaterial had had?

`IRenderpassIndependentPipeline` has all the functionality of `SMaterial` and most of `IMeshDataFormatDesc`.

**Comment by devshgraphicsprogramming** [comment]
> What is a purpouse of IRenderpassIndependentPipeline interface?
It has at all much to do, set vertex formats and bindings, it shares many enums for begginnig params of pipeline and more, but how does it combine with DescriptorSets and DescriptorSetLayouts?

There are two types of pipelines in Vulkan, a compute pipeline and a graphics pipeline.

They specify all the settings (programmable and fixed pipeline state) necessary to execute a `{Multi}{Indirect}Draw` or `{Indirect}Dispatch`, but none of the specific inputs (buffers, images, samplers) or outputs (buffers, images) to use.

We introduced a `RenderpassIndependentPipeline` because we disliked how Vulkan forced the user to know about the types and formats of Framebuffer Attachments (Render Targets in DirectX parlance) that will be used when creating the pipeline. This would have made it impossible to load models in a "screen agnostic way".

There will probably appear a `GraphicsPipeline` object in the future, but not right now.

Given a pipeline which is bound to a "pipeline bind point" (graphics or compute) you can bind Descriptor Sets to different set indices for different "pipeline bind points" (4 sets times 2 pipeline bind points) and that will make the shader use the Descriptors in the Set as shader inputs ({dynamic} UBO, {dynamic} SSBO, Uniform Texel Buffer, Storage Texel Buffer, Combined Image Samples, Storage Images) or outputs (SSBO, Storage Texel Buffer, Storage Images).

Descriptor Sets **do not provide** the vertex shader inputs, or fragment shader outputs (or subpass inputs).

**Comment by devshgraphicsprogramming** [comment]
> Well, IPipelineLayout itself doesn't have offsets, but it has smart ref counted dynamic array of SPushConstantRange that owns offset

Push Constants serve a similar purpose to a Uniform Buffer Object, however they serve as a fast path with regard to data upload from the CPU and data access from the GPU. They are implemented by taking some GPU core registers and pre-loading them with the appropriate values before the shader starts, register count is very limited so one needs to tightly specify the ranges of the "virtual memory" that will actually be used. The virtual memory range is also very small, just 128 bytes.

Push Constants are an alternative to an UBO where it performs really poorly, mostly very small and very frequent updates. Examples of which are:
- Global Object ID
- Material/Mesh flags implemented as bits
- Unique per DrawCall indices or bit-flags

To get a value from a UBO the following needs to happen:
1. The shader invocation needs to start
2. The location corresponding to the GPU memory holding the UBO must be determined
3. This memory needs to be fetched
4. On first run it won't be in the cache so 1000 cycle latency is incurred, otherwise just 30

To get a value from a Push Constant the following needs to happen
1. Before the Draw is recorded in the CPU-side command buffer the push constant update is recorded
2. When the Draw is recorded in the CPU-side command buffer, a register update is scheduled if push constant updated
3. Command Buffer is executed by GPU-side (driver or hardware) scheduler and dispatcher
4. The registers mapped to push constant ranges are updated with new values
5. Shader Invocation starts
6. Value already in registers, no additional operations on the GPU core are necessary


Push Constants are especially useful to specify a per-draw-call `uint` offset into a large UBO or SSBO that hold all the data for multiple draw calls. There is no way to get per-draw-call data from a large array without either:
- sending the index into the array as a push constant
- knowing the index into the array as a constant
- uploading the index into an UBO (very slow and stalling)
- using 1 descriptor set per each draw with same UBO bound at slightly different offsets
- using 1 descriptor set with "dynamic UBO" but this set needs to be rebound with new dynamic offsets before every draw-call

The last two options are impossible when "UBO binding offset alignment requirement" doesn't hold, for example you have an array of tighly packed 196 byte structs of per-mesh-buffer data, but the Graphics API only wants the UBO buffers to be bound with offsets aligned to 256.
So as you can see push constant is the only robust way to do this.

**Comment by AnastaZIuk** [comment]
> IRenderpassIndependentPipeline has all the functionality of SMaterial and most of
> IMeshDataFormatDesc.

It seems to me that there are changes though, I can't find for instance explicit way to set some usefull vector values (like diffuse) that `SMaterial` could set

**Comment by devshgraphicsprogramming** [comment]
> It seems to me that there are changes though, I can't find for instance explicit way to set some usefull vector values (like diffuse) that SMaterial could set

That stuff is not meaningless in the land of custom shaders.

The useful vector values were just dead variables attached to a struct that could be useful when setting shader uniforms, but they didn't do anything magical by themselves.

UBO/PushConstants can take that over now.

**Comment by devshgraphicsprogramming** [comment]
@AnastaZIuk is wiki up to date with this?
