### ISSUE TITLE
How to write good mesh loaders

### ISSUE THREAD

**Issue by AnastaZIuk** [buildaworldnet/IrrlichtBAW#384]

**Comment by devshgraphicsprogramming** [comment]
Tagging @Crisspl (subscribe plz)

**Comment by devshgraphicsprogramming** [comment]
# Split Your Loaders

Example, OBJ loader that loads textures from materials specified in an `.mtl` file. You should have 3+ Loaders:
1. OBJ loader that only reads `.obj` produces an `asset::ICPUMesh` necessarily invokes an MTL loader
2. MTL loader that only reads `.mtl` files and produces (or returns) a half-filled `asset::ICPURenderpassIndependentPipeline` (that OBJ can modify slightly for raster and vertex input parameters), naturally it invokes image loaders for needed textures. 
3. Texture Loaders for PNG, JPEG, etc. 

# If something cannot be passed within the returned asset bundle, use metadata to communicate between loaders

Example OBJ loader will probably want to know the material parameters that go with an MTL pipeline, but a pipeline does not include the actual parameters used such as "push constants" or "descriptor sets" only the layouts (generic material definition, not specific).

So the specific material definitions should come in the MTL-specific-metadata-derived-class that OBJ loader could use.

# Share `ICPUDescriptorSetLayout` as much as possible

You can over-declare descriptor set layouts, i.e. a set that has every single resource and more that a shader could use (all the textures, all the buffers for all shader types).

Its completely okay to have a descriptor in a set that is not used by the shader (not the other way round), and its okay not to populate a descriptor set binding that was specified in the layout as long as its not statically used by the shader (dead code).
(@Crisspl you may have to fix up the descriptor set code on OpenGL so it sets up the correct arguments for non-populated descriptor)

This helps the engine do less strenous resource rebinds (see Vulkan pipeline compatibility rules).

# Don't create copious amount of shaders, use Ubershader whenever possible (needs an engine extension, c.f. bottom of post)

Most formats such as STL, PLY, OBJ and even glTF declare a very limited set of materials.

You WILL find that instead of creating a new `ICPUSpecializedShader` for every single new `ICPURenderpassIndependentPipeline`, it would make much more sense to create the few `ICPUSpecializedShaders` and even `ICPUDescriptorSetLayout` as well as pipeline layouts in the constructor of the loader and cache them under a special path (similar to GLSL built-in includes) in the asset manager cache (then remove upon loader destruction).

You should be aiming to use as few `ICPUShader` as possible, and have them compile to SPIR-V, there isn't really a reason to not generate all the `ICPUShader`s you are going to use in the constructor of the pipeline loader.

## Only time when you can use/generate distinct ICPUShader objects (and DescriptorSetLayouts)

Only when specialization constants cannot achieve the material, examples:
1. different shader in-out blocks (vertex inputs, shader in-out blocks, fragment color outputs)
2. types of variables/descriptors or declarations (especially structs) need to change
3. when you have a reason to save on descriptor set bindings
(2 and 3 apply to descriptor set layouts)

Normally you can declare all the bindings you'll need for all descriptors, then if specialization constant disables their use, they can remain both in the unspecified in the layout and unpopulated in the set.

**Note:** When you have different vertex inputs or fragment outputs, you need a separate shader only when the shader-format changes, not the API. So you can still use the same shader if you change from `EF_R32G32_SFLOAT` to `EF_R8G8_UNORM`, because the input/output on the shader side is still a `vec2`. However if you change between `SFLOAT/UNORM/SNORM` and `INT` and `UINT`, then you'd have a problem because declaration goes from `vecN` to `ivecN` to `uvecN` in the GLSL.

## When Uber Shader is cheap

When you can pass the argument to an `if` or `switch` as a single push_constant or UBO (bit extraction allowed).

Note that switching between materials implemented via uber-shader does not cause unused descriptors to not be statically-used unlike implementing it via separate shader specializations.
**So the descriptor in the layout will have to be populated if only a flow-control-statement dependent on a push constant or UBO guards its usage.**
This might be undesireable especially for large buffers or textures as they might waste GPU cache, so sometimes specializing via separate specializations or even `ICPUShader`s is acceptable.

## Examples

Example 1; STL normal attribute plus optional color attribute so it would be logical to only create two vertex+fragment shader pair + descriptor layout and pipeline layout (one with per-vertex color, one without), even the pipeline you'd be returning could only come in two variants (not many parameters could change).

Example 2; OBJ only defines 10 illumination models, some of which we can't support out of the box (raytracing and similar) so there will probably only be a few permutations. You could collapse some of the permutations through the use of an uber-shader, the rest could be dealt with specialization constants. However OBJ vertex attributes may change (mostly presence, format irrelevant) so a few separate shaders may be needed. All in all, all the shaders and possibly even specializations + layouts can be precomputed for MTL/OBJ.

Example 3; BAW format allows to serialize everything without limits, so nothing can be precomputed.

# Use the Engines Built-in GLSL Headers

I do not want to see redefinitions of Frensel, GGX, Smith, etc. functions that we've already developed (for the BRDF explorer and others). Use the built-in headers!

If you need some functions or formulae, then **make a built-in GLSL header with them** and **check with @devshgraphicsprogramming if it can be added to the engine core (outside and before the loader, GLSL code shared with all)**, we want as **many GLSL headers in the engine core as possible**.

Even if it can't go into engine core, split out the common parts of your shaders into built-in includes, and register the built-in includes with the engine in the AssetLoader's constructor!

# Follow a standardized GLSL program structure

## Preprocessor Guard Everything

You want to guard every single function definition and descriptor set declaration with something akin to a header guard.
```glsl
#ifndef _FRAG_OUTPUT_DEFINED_
#define _FRAG_OUTPUT_DEFINED_
layout(location=0) out vec4 color;
#endif

#ifndef _FRAG_MAIN_DEFINED_
#define _FRAG_MAIN_DEFINED_
void main()
{
   BSDFIsotropicParams parameters;
   ... // generate parameters from lightPos, cameraPos and tangent-space
   Spectrum output = bsdf_eval(parameters);
   color = output.value;
}
#endif
```

Then by appending the appropriate forward declaration with the same guard, and postpending a definition, the programmer could override your shader's functions, just like this.

Append
```glsl
#define _FRAG_OUTPUT_DEFINED_
layout(location=0) out uint color;
#define _FRAG_MAIN_DEFINED_
void main();
```
Postpend
```glsl
void main()
{
   color = packUnorm4x8(vec4(1.0,0.0,0.0,0.0));
}
```

## Every shader needs 3 BSDF functions

@achalpandeyy might be interested.

```glsl
#ifndef _BSDF_DEFINED_
#define _BSDF_DEFINED_

// provides `BSDFIsotropicParams`, `BSDFAnisotropicParams`, `BSDFSample` and associated functions like `calc
#include "irr/builtin/glsl/bsdf/common.h"

// Spectrum can be exchanged to a float for monochrome
#define Spectrum vec3

//! This is the function that evaluates the BSDF for specific view and observer direction
// params can be either BSDFIsotropicParams or BSDFAnisotropicParams 
Spectrum bsdf_cos_eval(in BSDFIsotropicParams params)
{
...
}

//! generates a incoming light sample position given a random number in [0,1]^2 + returns a probability of the sample being generated (ideally distributed exactly according to bsdf_cos_eval)
BSDFSample bsdf_cos_gen_sample(in vec2 _sample)
{
...
}

//! returns bsdf_cos_eval/Probability_of(bsdf_cos_gen_sample) but without numerical issues
Spectrum bsdf_cos_sample_eval(out vec3 L, in ViewSurfaceInteraction interaction, in vec2 _sample)
{
   // sample evil implementation (0 div 0 possible and bad efficiency)
   BSDFSample _sample = bsdf_cos_gen_sample(smpl);
   L = _sample.L;
   return bsdf_cos_eval(calcBSDFIsotropicParams(interaction,_sample.L))/_sample.probability;
}

#endif
```

See https://github.com/buildaworldnet/IrrlichtBAW/issues/384#issuecomment-546903906 for what that `common.glsl` could look like.

# Do not, for the love of God, try to implement lighting in your asset's shaders!!!

Lighting (deferred, GI, forward, direct, shadowing, etc.) is the job of the renderer/programmer who knows what they are doing.

The material shaders shall provide **BSDF and Importance Sampling Functions Only**.

Default shader should visualize a simple non shadowed point-light of constant-world-space-intensity positioned at the eye/camera (like current example nr. 5 etc.).

If you know that your material is intended to be transparent, you can enable blending (additive or overlay/`ONE_MINUS_SRC_ALPHA`), I prefer precomputed RGB blend function (so you already multiply source_rgb by source_alpha in the shader).

**Corollary**, the fragment shader will always output a single `vec4` color.

For the benefit of mirror/conductor materials, environment map lighting / IBL is allowed.

So your shader for all loaders will most probably be
```cpp
#ifndef _FRAG_MAIN_DEFINED_
#define _FRAG_MAIN_DEFINED_
void main()
{
   BSDFIsotropicParams parameters;
   // your BSDFSample is direction towards light (camera)
   ... // generate parameters from lightPos, cameraPos, viewDir and tangent-space

   // might be inf by chance
   vec3 totalColor = bsdf_eval(parameters);

   if (specContantUsingIBL)
   {
      for (uint i=0u; i<specConstantMaxIBLSamples; i++)
      {
         vec2 _sample2d = gen_2d_sample(i);
         totalColor += bsdf_cos_sample_eval(tspaceViewDir,_sample2d);
      }
   }

   color = totalColor;
}
#endif
```

# Required engine extensions (@AnastaZIuk  and @Crisspl )

## Immutable asset

All the `asset` mutators for all Assets (non-const getters, etc.) would need some sort of a run-time guard so that a user cannot modify a precomputed and shared "asset" like the pipelines I mentioned above.

Actually we could use the existing loader override system with the duplication/caching flags to provide control whether user wants possibly precomputed immutable asset from a cache or a mutable duplicated copy.
But still need a system to know if the cached item is immutable.

## General AssetLoader Parameter flag whether to return SPIR-V or GLSL shaders

This is to make the above scenario of replacing parts of shaders with custom functions a reality, as we'd naturally need to recompile the GLSL if function definitions were to be swapped.

Default return type shall be SPIR-V (will be faster, as most loaders shall have a precomputed small set of `ICPUShader`s to use).

## Left vs. Right handed model loading flag

Something I feel would be useful now that the engine supports right-handed cameras. Example; OBJ loader flips from right hand to left hand, which means sponza looks right only with a left-hand camera, would be nice to be able to load meshes in right-hand mode as well (flip their positions and normals around X while loading).

**Comment by devshgraphicsprogramming** [comment]
@Crisspl  backed up comments

```
just do a built-in include with the default definition of a per-camera and per-scene node descriptor set (UBOs only really)
@devshgraphicsprogramming
devshgraphicsprogramming 22 days ago Author Collaborator

you can also kill all draw2D* functions
@devshgraphicsprogramming
devshgraphicsprogramming 12 days ago Author Collaborator

@Crisspl still need to nuke the transformation state stuff (just provide a built-in GLSL include with a default descriptor set)
@Crisspl
Crisspl 11 days ago Contributor

i dont see how "built-in GLSL include with a default descriptor set" and "transformation state stuff" are substitutes?
@devshgraphicsprogramming
devshgraphicsprogramming 10 days ago Author Collaborator

First replace everything with matrix***SIMD types, then
For people and parts of the engine only using the video namespace

whatever/path/we/have/for/builtins/DefaultCameraData.glsl

struct DefaultCameraData
{
    mat4x3 view;
    mat4x3 viewInverse;
    mat4 proj;
    mat4 projInverse;
    mat4 projView;
    mat4 projViewInverse;
};

whatever/path/we/have/for/builtins/DefaultSceneNodeData.glsl

struct DefaultSceneNodeData
{
    mat4x3 view;
    mat4x3 viewInverse;
    mat4 proj;
    mat4 projInverse;
    mat4 projView;
    mat4 projViewInverse;
};

whatever/path/we/have/for/builtins/defaultCameraUBO/location/${loc}.glsl

#include "whatever/path/we/have/for/builtins/DefaultCameraData.glsl"
layout(set=1, location=${loc}, row_major) DefaultPerViewUBO
{
    DefaultCameraData data;
} defaultPerViewUBO;

whatever/path/we/have/for/builtins/defaultSceneNodeUBO/location/${loc}.glsl

#include "whatever/path/we/have/for/builtins/DefaultSceneNodeData.glsl"
layout(set=1, location=${loc}, row_major) DefaultPerSceneNodeUBO
{
    DefaultSceneNodeData data[];
} defaultPerSceneNodeUBO;

Then people will need to know to push new data (via streaming update or upload everything up-front then rebind at different offset before every draw).
Fixing the scene namespace

Will be piss-easy. We allow each scene node to hold a descriptor set + offsets, and also the scene manager (the global desc set).

class ISceneNode
{
...
setDescriptorSet(...) {}
getDescriptorSet(...) {}
setDynamicOffsets(...) {}
getDynamicOffsets(...) {}
...
IGPUDescriptorSet* descSet;
core::refctd_dynamic_array<uint32_t> dynamicOffsets;
...
}

Now the difference is that during the override of ISceneNode::render() the camera scene node will bind its descriptor set to slot 1, but a regular scene node will bind to slot 2.

Any meshbufferscenenode will take the descriptor set + dynamic offsets attached to a meshbuffer and bind it to slot 3, as well as push the constants just before the draw.

And obviously ISceneManager::drawAll() shall begin by binding descriptor set to slot 0.
How the data will be updated

We will need a scene::DescriptorSetUpdater class and a default instantiation of it that will run after ISceneNode::OnAnimate() is finished, think of it like an animation call-back.

I see a method like scene::DescriptorSetUpdater::update(scene::ISceneNode*,video::IGPUDescriptorSet*,core::smart_refctd_dynamic_array<uint32_t>* offsets)

The default one for cameras will stream update the buffer in location 0 at offset assigned with the matrices as expected by the DefaultPerViewUBO.

The default one for mesh scene nodes will do the same for DefaultPerSceneNodeUBO.

User can derive and make a different descriptor-set-updater.

I plan to replace this prototype with something much faster when I come to do #96 and bucket-rendering.
@devshgraphicsprogramming
devshgraphicsprogramming 3 days ago Author Collaborator

@Crisspl can you back these comments up somewhere, I'm scared I'll have to go over it again in the near future when you fix irr::scene

@AnastaZIuk read this thread, relevaant to the loader refactor.

```

**Comment by AnastaZIuk** [comment]
Who does handle `ICPUSpecializedShader` putting to pipeline process? And who does manage `ICPUShader` loading shader's source code to a buffer?

**Comment by AnastaZIuk** [comment]
What is `SPIR-V` in a few sentences?. spriv.h contains plenty enums for some configurations (no idea)

**Comment by AnastaZIuk** [comment]
How does a stream of metadata in our engine look like? Is there any convention for streaming? I think there is for sure

**Comment by devshgraphicsprogramming** [comment]
> What is SPIR-V in a few sentences?. spriv.h contains plenty enums for some configurations (no idea)

GLSL compiled to a portable Intermediate Representation (something that kind-of looks like assembly).

**Comment by devshgraphicsprogramming** [comment]
>Who does handle ICPUSpecializedShader putting to pipeline process?

You mean "who's responsibility is the creation of the chain of objects from ICPUSpecializedShader up until the pipeline object"?

Its easy, the user can programmatically/procedurally (without loading any assets) create all of these, like in the example `03.GPUMesh`.

However `IAssetLoaders` that return an `ICPUMesh`, `ICPUMeshBuffer` or `ICPURenderpassIndependentPipeline` must construct (or return cached) pipeline objects with reasonable default shaders attached.

The expectation though is that the user will have their own rendering technique in mind (such as deferred renderin) and will "more often than not" replace the pipeline entirely (maybe while keeping some of the initial state in the one that will replace the original).

We should provide a nice function in the SPIR-V introspection class to attempt to create a reasonable ICPURenderpassindependentPipeline for a collection of shaders.

> And who does manage ICPUShader loading shader's source code to a buffer?

You can read it directly byte-for-byte from files you know to contain SPIR-V ( we should actually make two IAssetLoaders, one that loads `.frag,.vert,.geom,.ctrl,.eval,.comp,.glsl` and another that loads `.spv`)

If you have raw GLSL (in `const char*` or in a file) then you can use the `IGLSLCompiler` to compile it into an `ICPUShader`

**Comment by devshgraphicsprogramming** [comment]
> How does a stream of metadata in our engine look like? Is there any convention for streaming? I think there is for sure

What streaming?

**Comment by AnastaZIuk** [comment]
> You mean "who's responsibility is the creation of the chain of objects from ICPUSpecializedShader up until the pipeline object"?

That's it

> However IAssetLoaders that return an ICPUMesh, ICPUMeshBuffer or 
> ICPURenderpassIndependentPipeline must construct (or return cached) pipeline objects with 
> reasonable default shaders attached.

So pipeline objects can be modified after shader attachment?

> What streaming?

I mean data that has to be passed through metadata stream, yeah? There must be a way to do that, but how does it work? How does it look like and what is the convention for doing so?

**Comment by devshgraphicsprogramming** [comment]
> So pipeline objects can be modified after shader attachment?

Only `ICPU*Pipeline`s, the GPU objects are immutable, as in you must set them up with correct state in the constructor/creation function as you won't be able to change it later.

> I mean data that has to be passed through metadata stream, yeah? There must be a way to do that, but how does it work? How does it look like and what is the convention for doing so?

Stream is the wrong word, shouldn't be used.

I can give you a worked example

definition:
https://github.com/buildaworldnet/IrrlichtBAW/blob/mitsuba/ext/MitsubaLoader/CGlobalMitsubaMetadata.h

creation and attachment:
https://github.com/buildaworldnet/IrrlichtBAW/blob/mitsuba/ext/MitsubaLoader/CMitsubaLoader.cpp#L139

usage:
https://github.com/buildaworldnet/IrrlichtBAW/blob/mitsuba/ext/MitsubaLoader/CMitsubaLoader.cpp#L207

**Comment by AnastaZIuk** [comment]
Is there any forced format of writing loaders? For instance, Is it desired to always use some classes regardless of loader destination (for example, .x loader may load .x format and implement a specific way of such loading process, but It uses some classes, that every loader should use). Is there any convention for that?

**Comment by devshgraphicsprogramming** [comment]
> Is there any forced format of writing loaders? For instance, Is it desired to always use some classes regardless of loader destination (for example, .x loader may load .x format and implement a specific way of such loading process, but It uses some classes, that every loader should use). Is there any convention for that?

You should be using the `IAssetManager` reference to set metadata on a shader, and `interm_getAssetInHierarchy` to load any dependencies (texture for a descriptor set, shader for a pipeline).. never another `IAssetLoader` directly.

Any other questions regarding this?

**Comment by devshgraphicsprogramming** [comment]
# BRDF Params

```glsl
// do not use this struct in SSBO or UBO, its wasteful on memory
struct DirAndDifferential
{
   vec3 dir;
   // differentials at origin, I'd much prefer them to be differentials of barycentrics instead of position in the future
   mat3x2 dPosdScreen;
};

// do not use this struct in SSBO or UBO, its wasteful on memory
struct ViewSurfaceInteraction
{
   DirAndDifferential V; // outgoing direction, NOT NORMALIZED; V.dir can have undef value for lambertian BSDF
   vec3 N; // surface normal, NOT NORMALIZED
};

// do not use this struct in SSBO or UBO, its wasteful on memory
struct BSDFSample
{
   vec3 L;  // incoming direction, normalized
   float probability; // for a single sample (don't care about number drawn)
};


// do not use this struct in SSBO or UBO, its wasteful on memory
struct BSDFIsotropicParams
{
   float NdotL;
   float NdotL_squared;
   float NdotV;
   float NdotV_squared;
   float VdotL; // same as LdotV
   float NdotH;
   float VdotH; // same as LdotH
   // left over for anisotropic calc and BSDF that want to implement fast bump mapping
   float LplusV_rcpLen;
   // basically metadata
   vec3 L;
   ViewSurfaceInteraction interaction;
};

// do not use this struct in SSBO or UBO, its wasteful on memory
struct BSDFAnisotropicParams
{
   BSDFIsotropicParams isotropic;
   float TdotL;
   float TdotV;
   float TdotH;
   float BdotL;
   float BdotV;
   float BdotH;
   // useless metadata
   vec3 T;
   vec3 B;
};
```

# Parameter Getters

Only most performant getter functions (with identities) are provided (in a core API engine built-in)
```glsl
// chain rule on various functions (usually vertex attributes and barycentrics)
vec2 applyScreenSpaceChainRule1D3(in vec3 dFdG, in mat3x2 dGdScreen)
{
   return dFdG*dGdScreen;
}
mat2 applyScreenSpaceChainRule2D3(in mat2x3 dFdG, in mat2 dGdScreen)
{
   return dFdG*dGdScreen;
}
mat3x2 applyScreenSpaceChainRule3D3(in mat3x3 dFdG, in mat3x2 dGdScreen)
{
   return dFdG*dGdScreen;
}
mat4x2 applyScreenSpaceChainRule4D3(in mat4x3 dFdG, in mat3x2 dGdScreen)
{
   return dFdG*dGdScreen;
}

// only in the fragment shader we have access to implicit derivatives
ViewSurfaceInteraction calcFragmentShaderSurfaceInteraction(in vec3 CamPos, in vec3 SurfacePos, in vec3 Normal)
{
   ViewSurfaceInteraction interaction;
   interaction.V.dir = CamPos-SurfacePos;
   interaction.V.dPosdScreen[0] = dFdx(SurfacePos);
   interaction.V.dPosdScreen[1] = dFdy(SurfacePos);
   interaction.N = Normal;
   return interaction;
}
// when you know the projected positions of your triangles (TODO: should probably make a function like this that also computes barycentrics)
ViewSurfaceInteraction calcBarycentricSurfaceInteraction(in vec3 CamPos, in vec3 SurfacePos[3], in vec3 Normal[3], in float Barycentrics[2], in vec2 ProjectedPos[3])
{
   ViewSurfaceInteraction interaction;

   // Barycentric interpolation = b0*attr0+b1*attr1+attr2*(1-b0-b1)
   vec3 b = vec3(Barycentrics[0],Barycentrics[1],1.0-Barycentrics[0]-Barycentrics[1]);
   mat3 vertexAttrMatrix = mat3(SurfacePos[0],SurfacePos[1],SurfacePos[2]);
   interaction.V.dir = CamPos-vertexAttrMatrix*b;
   // Schied's derivation - modified
   vec2 to2 = ProjectedPos[2]-ProjectedPos[1];
   vec2 to0 = ProjectedPos[0]-ProjectedPos[1];
   float d = 1.0/determinant(mat2(to2,to1)); // TODO double check all this
   mat3x2 dBaryd = mat3x2(vec3(v[1].y-v[2].y,to2.y,to0.y)*d,-vec3(v[1].x-v[2].x,to2.x,t0.x)*d);
   //
   interaction.dPosdScreen = applyScreenSpaceChainRule3D3(vertexAttrMatrix,dBaryd);

   vertexAttrMatrix = mat3(Normal[0],Normal[1],Normal[2]);
   interaction.N = vertexAttrMatrix*b;

   return interaction;
}
// when you know the ray and triangle it hits
ViewSurfaceInteraction  calcRaySurfaceInteraction(in DirAndDifferential rayTowardsSurface, in vec3 SurfacePos[3], in vec3 Normal[3], in float Barycentrics[2])
{
   ViewSurfaceInteraction interaction;
   // flip ray
   interaction.V.dir = -rayTowardsSurface.dir;
   // do some hardcore shizz to transform a differential at origin into a differential at surface
   // also in barycentrics preferably (turn world pos diff into bary diff with applyScreenSpaceChainRule3D3)
   interaction.V.dPosdx = TODO;
   interaction.V.dPosdy = TODO;

   vertexAttrMatrix = mat3(Normal[0],Normal[1],Normal[2]);
   interaction.N = vertexAttrMatrix*b;

   return interaction;
}

// will normalize all the vectors
BSDFIsotropicParams calcBSDFIsotropicParams(in ViewSurfaceInteraction interaction, in vec3 L)
{
   float invlenV2 = inversesqrt(dot(V,V));
   float invlenN2 = inversesqrt(dot(N,N));
   float invlenL2 = inversesqrt(dot(L,L));

   BSDFIsotropicParams  params;

   // totally useless vectors, will probably get optimized away by compiler if they don't get used
   // but useful as temporaries
   params.interaction.V.dir = interaction.dir.v*invlenV2;
   params.interaction.N = interaction.N*invlenN2;
   params.L = L*invlenL2;

   // this stuff only works with normalized L,N,V
   params.NdotL = dot(params.interaction.N,params.L);
   params.NdotL_squared = params.NdotL*params.NdotL;
   params.NdotV = dot(params.interaction.N,params.interaction.V.dir);
   params.NdotV_squared = params.NdotV*params.NdotV;

   params.VdotL = dot(params.interaction.V.dir,params.L);
   params.LplusV_rcpLen =inversesqrt(2.0 + 2.0*params.VdotL) ;

   // this stuff works unnormalized L,N,V
   params.NdotH = (params.NdotL+params.NdotV)*LplusV_rcpLen;
   params.VdotH = LplusV_rcpLen + LplusV_rcpLen*LdotV;

   return params;
}
// get extra stuff for anisotropy, here we actually require T and B to be normalized
BSDFAnisotropicParams calcBSDFAnisotropicParams(in BSDFIsotropicParams isotropic, in vec3 T, in vec3 B)
{
   BSDFAnisotropicParams params;
   params.isotropic = isotropic;

   // meat
   params.TdotL = dot(T,isotropic.L);
   params.TdotV = dot(T,isotropic.interaction.V.dir);
   params.TdotH = (params.TdotV+params.TdotL)*isotropic.LplusV_rcpLen;
   params.BdotL = dot(B,isotropic.L);
   params.BdotV = dot(B,isotropic.interaction.V.dir);
   params.BdotH = (params.BdotV+params.BdotL)*isotropic.LplusV_rcpLen;

   // useless stuff we keep just to be complete
   params.T = T;
   params.B = B;

   return params;
}
```

**Comment by devshgraphicsprogramming** [comment]
`bsdf_cos_sample_eval` should never, ever, ever, produce an L vector (towards light) that is then subsequently normalized (so it cannot use `calcBSDFIsotropicParams` at any point).

**Comment by AnastaZIuk** [comment]
Offtopic associated with **CBAWMeshFileLoader**
How does CBAW handle single data? There are many blobs it handles, there is even a special manager for blobs, and many macros handling blobs but I can't see actually anything with loading data such a position vector.

**Comment by devshgraphicsprogramming** [comment]
> How does CBAW handle single data? There are many blobs it handles, there is even a special manager for blobs, and many macros handling blobs but I can't see actually anything with loading data such a position vector.

We dump entire engine classes and their contents to file, basically a memcpy with pointer patching.

**Comment by devshgraphicsprogramming** [comment]
@AnastaZIuk is wiki up to date with this?
