### ISSUE TITLE
Address allocators should be copy-able

### ISSUE THREAD

**Issue by Crisspl** [buildaworldnet/IrrlichtBAW#482]
Or any other way to copy state from other addr allocator object. Mandatory for creating fully functioning `IGPUVirtualTexture` from `ICPUVirtualTexture`.

**Comment by devshgraphicsprogramming** [comment]
the constructors that take an r-value reference to the address allocator and allow you to specify a new reserved space, address offset and align offset are the ones that will allow you to move an address allocator.

This is actually how address allocator resize (grow/shrink) is implemented for the more complex meta-allocator types.

```cpp

            AddressAllocatorBase(CRTP&& other, void* newReservedSpc) :
                    reservedSpace(nullptr), addressOffset(invalid_address), alignOffset(invalid_address),
                    maxRequestableAlignment(invalid_address), combinedOffset(invalid_address)
            {
                operator=(std::move(other));
                reservedSpace = newReservedSpc;
                #ifdef _IRR_DEBUG
                    // reserved space has to be aligned at least to SIMD
                    assert((reinterpret_cast<size_t>(reservedSpace)&(_IRR_SIMD_ALIGNMENT-1u))==0ull);
                #endif // _IRR_DEBUG
            }
            AddressAllocatorBase(CRTP&& other, void* newReservedSpc, _size_type newAddressOffset, _size_type newAlignOffset) :
                    AddressAllocatorBase(std::move(other),newReservedSpc)
            {
                addressOffset = newAddressOffset;
                alignOffset = newAlignOffset;
                combinedOffset = addressOffset+alignOffset;
            }
```

Not really sure why you'd need to copy an address allocator, but you could duplicate the definition of these two constructors in every address allocator (most will only do perfect forwarding) and make a version that is `explicit` and takes a `const CRTP&` instead of a `CRTP&&`
