### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by kilbith** [buildaworldnet/IrrlichtBAW#6]
Compiler : GCC 6.3
Is is not permitted to use `dynamic_cast` with the compiler flag `-fno-rtti`

**Comment by devshgraphicsprogramming** [comment]
on which build target did this happen?

**Comment by kilbith** [comment]
Sorry, release build.

**Comment by devshgraphicsprogramming** [comment]
but using which method of building?

**Comment by kilbith** [comment]
A simple `make -j4`

**Comment by devshgraphicsprogramming** [comment]
only codeblocks (Linux Static) and visual studio projects work

makefile is only for linux server no opengl build

use cbp2make if you really need a makefile and cant use/install code::blocks

**Comment by kilbith** [comment]
Made a Makefile with cbp2make this time. I'm getting another error:

```
/usr/lib/gcc/x86_64-redhat-linux/7/include/pmmintrin.h:56:1: error: la mise en ligne a échoué dans l'appel à always_inline « __m128 _mm_hadd_ps(__m128, __m128) »: target specific option mismatch
 _mm_hadd_ps (__m128 __X, __m128 __Y)
 ^~~~~~~~~~~
```

**EDIT:** I solved this by adding `-msse4.1`

**Comment by kilbith** [comment]
Also, some of your `#include` are wrong in `coreutil.cpp`, must be changed to : 

```C
#include "utf8/source/utf8.h"
#include "convert_utf/ConvertUTF.h"
```

And finally a truckload of errors about that : 

```
aesGladman/sha2.cpp:392:1: error: conversion réductrice de « 13096744586834688815 » depuis « long unsigned int » vers « sha2_64t {aka long int} » à l'intérieur de { } [-Wnarrowing]
 };
 ^
```

**Comment by devshgraphicsprogramming** [comment]
_mm_hadd_ps needs -msse4.1 ??

will take note about the utr8 stuff

are you converting the right target with cbp2make?
because the correct one (Linux fast math static) for sure has msse3 and sha2 does not give error (because -std=c++03 is specified as an option)


aesGladman/sha2.cpp:392:1: error: conversion réductrice de « 13096744586834688815 » depuis « long unsigned int » vers « sha2_64t {aka long int} » à l'intérieur de { } [-Wnarrowing]
 This needs the -std=c++03 option

**Comment by devshgraphicsprogramming** [comment]
New build system is coming.
