### ISSUE TITLE
SDL2 support

### ISSUE THREAD

**Issue by bkeys** [buildaworldnet/IrrlichtBAW#7]
Did you ever manage to get SDL2 support for IrrBaw?

**Comment by devshgraphicsprogramming** [comment]
not on the top of my priority list right now...

You'e more than welcome to branch :D

**Comment by devshgraphicsprogramming** [comment]
Moving to the forefront of focus now.

Remove all devices except for EDT_CONSOLE and EDT_SDL2 (rename EDT_SDL), remove even the EDT_BEST enum.

Develop an SDL2 device while keeping in mind forward-compatibility for Joysticks, and especially Multi-touch.

VR controller input is a job for OpenXR not SDL2.

SDL2 device must be able to create multiple OpenGL core profile contexts, which share resources and if-possible the auxilary contexts should have their own default framebuffers (off-screen) like in the windows and linux drivers. OpenGL function retrieval may not be necessary (maybe COpenGLExtensionHandler can do that already).

SDL2 device should also have some stub code for Vulkan instance and device creation and function pointer retrieval.

EDT_BURNINGSVIDEO should be removed, but a special functionality to IrrlichtDevice should be added called `blitSoftwareImageToScreen` which should take a CImageData, a source rectangle, a destination position and an optional clipping rectangle (by default the rectangle of the screen) in order to blit the chosen part of the CImageData onto the screen. The function is allowed to use locking and unlocking, and be generally slow. 
The sole purpose is to replace the only functionality of EDT_BURNINGSVIDEO that we use which is `IVideoDriver::draw2DImage`.

**Comment by devshgraphicsprogramming** [comment]
@Crisspl how do we update our CMake build system so that:
- Developer on Windows doesn't have to do weird stuff to find SDL2
- Developer on Linux builds against shared library SDL2 so that it works nicely with Steam?

Maybe put SDL2 source in 3rdparty?
On Windows should we make a `examples_tests/common` folder that not only holds media but also dlls?

**Comment by manhnt9** [comment]
In my [Saga3D](https://gitlab.com/InnerPieceOSS/Saga3D/) project, non-VS users can easily install any dependent packages by using MSYS2. Visual Studio users can use vcpkg for the same task. Now my lib build flawlessly on Windows and Linux. I don't like to handle dependencies manually so I use tools.

**Comment by devshgraphicsprogramming** [comment]
I'm not a great fan of these approaches (package managers), especially if you're working on 5 different projects that require 5 different versions of the same library dependency.

**Comment by devshgraphicsprogramming** [comment]
Also our CMake build system supports CMake FIND, so if you're using a package manager which works with CMake then openssl and SDL2 should be able to be found.

**Comment by manhnt9** [comment]
> I'm not a great fan of these approaches (package managers), especially if you're working on 5 different projects that require 5 different versions of the same library dependency.

Well that sounds like a headache to me, I would really try to make them use same versions. Any special issues that lead you to that?

**Comment by devshgraphicsprogramming** [comment]
Because I'm not the boss of these projects.

**Comment by devshgraphicsprogramming** [comment]
This might be useful info for windows
https://trenki2.github.io/blog/2017/06/02/using-sdl2-with-cmake/

**Comment by devshgraphicsprogramming** [comment]
@manhnt9 can VCPKG be integrated with CMake so that CMake `find_package` is able to find stuff installed with vcpkg?

**Comment by manhnt9** [comment]
Of course, and user will need to add `-DCMAKE_TOOLCHAIN_FILE=_VCPKG_INSTALL_PATH_/scripts/buildsystems/vcpkg.cmake` to CMake call for that.

**Comment by devshgraphicsprogramming** [comment]
is there any way to do this with CMAKE gui?

**Comment by manhnt9** [comment]
I think this will work (not 100% certain). https://stackoverflow.com/questions/29982505/setting-a-cross-compiler-file-using-the-cmake-gui

**Comment by devshgraphicsprogramming** [comment]
```cpp
class IGraphicsAPI
{
};

class IGraphicsAPIAccessor
{
// return alphabetically sorted extension names
virtual core::SRange<const char*> getExtensions() const =0;

//
virtual void* loadCoreFunction(const char* name);

//
virtual void* loadExtensionFunction(const char* name);
};

class IVulkanAccessor : public IGraphicsAPIAccessor;
class IOpenGLAccessor : public IGraphicsAPIAccessor;
class IOpenGLESAccessor : public IGraphicsAPIAccessor;
```

This is what I want the end result to be
```cpp
// get basic stuff
smart_refctd_ptr<system::IOperatingSystem> os = COperatingSystemSDL2::create(); // get core count, mem size, cpu features, start a thread, mutexes, semaphores, load a DLL etc.
smart_refctd_ptr<system::IFilesystem> fs = CFilesystemSDL2::create(os); // file, URL stuff, etc.

// this we only need if we want to do rendering
smart_refctd_ptr<system::IGPUAccessor> gpus = CGPUAccessorSDL2::create(os);
IGPUAPI* gpuApi = gpu->getOpenGL(); // getOpenGLES, getVulkan, getCUDA, getOpenCL, etc.
SRange<IGPUAPICapabilityReport*> reports = gpuApi->getDeviceReports(); // IGPUAPICapabilityReport can tell us what other `IGPUAPICapabilityReport` we can share resources with or group with
// user defined heuristics
IGPUAPICapabilityReport* gpu = chooseBestGPU(reports);

// this we only need if we want to display a window
IWindow::CreationParameters params;
params.os = os;
if (hardwareAcceleratedRendering) // this we only need if we want to render to the said window
{
    params.windowConfig = getBestWindowConfig(gpu,resolution,...); // this is user defined too
    params.targetGPUs = {&gpu,&gpu+1};
}
smart_refctd_ptr<system::IWindow> window = CWindowSDL2::create(std::move(params));
// to be able to render to a window, one needs a swapchain
smart_refctd_ptr<video::ISwapchainCreateInfo> swapInfo = window->getSwapChainCreateInfo();

// actually start using the GPU
IGraphicsAPIAccessor::CreationParameters params;
params.swapchains = {&swapInfo,&swapInfo+1};
params.sharingAPIs = {nullptr,nullptr}; // this is for OpenCL/CUDA 
smart_refctr_ptr<video::IGraphicsAPIAccessor> gpuApi = COpenGLAccessor::create(std::move(params));

// now we can start the work.
auto* swapchain = gpuAPI->getSwapchain(swapInfo);
auto* family = gpuAPI->getQueueFamily();
auto queue = family->createQueue();

// create other subsystems we might like
auto assMgr = IAssetManager::create(os);
auto input = CInputSDL2::create(os,window); /*theoretically window could be null for some platforms, global joysticks, etc. */
auto smgr = CSceneManager::create(os,window,queue);
```

**Comment by devshgraphicsprogramming** [comment]
SDL2 is a horrible library for window creation and OpenGL context creation.

Only semi-decent for input handling.

However Nabla will support an SDL2 window and a special SDL2 swapchain.
